export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH = 'AUTH_REFRESH';

export const SHOPS_LIST_REQUEST = 'SHOPS_LIST_REQUEST';
export const SHOPS_LIST_SUCCESS = 'SHOPS_LIST_SUCCESS';
export const SHOPS_LIST_FAIL = 'SHOPS_LIST_FAIL';

export const SHOP_SELECTION_SUCCESS = 'SHOP_SELECTION_SUCCESS';
export const SHOP_SELECTION_FAIL = 'SHOP_SELECTION_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CURRENT_REQUEST_STARTED = 'CURRENT_REQUEST_STARTED';
export const CURRENT_REQUEST_SUCCESS = 'CURRENT_REQUEST_SUCCESS';
export const CURRENT_REQUEST_FAIL = 'CURRENT_REQUEST_FAIL';

export const ACCEPTED_REQUEST_STARTED = 'ACCEPTED_REQUEST_STARTED';
export const ACCEPTED_REQUEST_SUCCESS = 'ACCEPTED_REQUEST_SUCCESS';
export const ACCEPTED_REQUEST_FAIL = 'ACCEPTED_REQUEST_FAIL';

export const CUSTOMER_REQUEST_STARTED = "CUSTOMER_REQUEST_STARTED";
export const CUSTOMER_REQUEST_SUCCESS = "CUSTOMER_REQUEST_SUCCESS";
export const CUSTOMER_REQUEST_FAIL = "CUSTOMER_REQUEST_FAIL";