export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH = 'AUTH_REFRESH';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CURRENT_REQUEST_SUCCESS = 'CURRENT_REQUEST_SUCCESS';
export const CURRENT_REQUEST_FAIL = 'CURRENT_REQUEST_FAIL';

export const ACCEPTED_REQUEST_SUCCESS = 'ACCEPTED_REQUEST_SUCCESS';
export const ACCEPTED_REQUEST_FAIL = 'ACCEPTED_REQUEST_FAIL';